apiVersion: v1
kind: Service
metadata: 
  name: voting-svc-svc
  labels:
    name: voting-app
    app: voting-application
spec: 
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector: 
    name: voting-app
    app: voting-application

        
