apiVersion: v1
kind: Pod
metadata: 
  name: worker-app-pod
  labels:
    name: worker-app
    app: voting-application
spec: 
  containers:
    - name: worker-container
      image: kodekloud/examplevotingapp_worker:v1
      ports:
        - containerPort: 80
