version: '3'
services:
  dev-site: 
    image: ubuntu
    ports: 
      - '5000:80'
    networks:
      - frond-end
    volumes: 
     - 'site-database:/opt/'

networks:
  frond-end:
    driver: bridge
  back-end:
    driver: bridge
volumes: 
  site-database:
