apiVersion: v1
kind: Pod
metadata: 
  name: uk-site
  labels:
    managedby: himanshu
    app: education
    env: Prod
spec: 
  containers: 
    - name: uk-site-cont
      image: nginx
      ports:
        - containerPort: 80
