apiVersion: v1
kind: Service
metadata:
  name: ps-cluster-site
spec:
  type: ClusterIP
  clusterIP: 10.96.1.100
  ports:
    - port: 80
      targetPort: 80
  selector:
    managedby: himanshu
    app: ps-dev
    env: Prod

