apiVersion: apps/v1
kind: Deployment
metadata:
  name: uk-site
  labels:
    managedby: himanshu
    app: education-site
    env: Prod
spec:
  selector:
    matchLabels:
      managedby: himanshu
      app: education-site
      env: Prod
  template:
    metadata: 
      name: uk-site
      labels:
        managedby: himanshu 
        app: education-site
        env: Prod
    spec: 
      containers: 
        - name: nginx
          image: nginx:1.26
          ports:
            - containerPort: 80
  replicas: 10
