version: '3'
services: 
  nurun-uk-site:
    image: nginx
    restart: always
      #    networks:
      #      - pub-dmz
      #    volumes:
      #      - hp

      #networks: 
      #  pub-dmz:
      #    driver: bridge
      #volumes: 
      #  hp:
  
